# Generated by Django 4.2.18 on 2025-01-28 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='canvas_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='is_game_artwork',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='vector_embedding',
            field=models.JSONField(blank=True),
        ),
    ]
