# Generated by Django 4.2.18 on 2025-01-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0002_alter_artwork_canvas_data_alter_artwork_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artworks/'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='vector_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
